apiVersion: v1
kind: Namespace
metadata:
  name: bdaybot
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
  name: bdaybot
  namespace: bdaybot
spec:
  schedule: 55 6 * * *
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - image: josefuentes/bdaybot-slack
            imagePullPolicy: Always
            name: bdaybot
            args:
              - -config
              - /config/config.json
              - -userTokenFile
              - /token/token.json
            volumeMounts:
            - mountPath: /config
              name: bdaybot-config
              readOnly: true
            - mountPath: /token
              name: bdaybot-token
              readOnly: true
          volumes:
          - name: bdaybot-config
            secret:
              defaultMode: 420
              secretName: bdaybot-config
          - name: bdaybot-token
            secret:
              defaultMode: 420
              secretName: bdaybot-token
